version: "3"

services:
  firefox:
    image: selenium/node-firefox:4.1.2-20220217
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=10
    ports:
      - "6902:5900"
      - "7902:7900"
  #    profiles: [ "selenium","all" ]

  selenium-hub:
    image: selenium/hub:4.1.2-20220217
    container_name: selenium-hub
    ports:
      - "4444:4444"
  #    profiles: [ "selenium","all" ]

  maven:
    image: maven:3.6.3-openjdk-8
    container_name: maven
    volumes:
      - .:/usr/src/mymaven
    command: mvn -f /usr/src/mymaven clean verify
    network_mode: "host"
#    profiles: [ "all" ]
